# Generated by Django 6.1.1 on 2026-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
